# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSA.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("#centralwidget {border-image: url(:/Images/arnames2.png) 0 0 0 0 stretch stretch;}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Benton = QtWidgets.QLabel(self.centralwidget)
        self.Benton.setGeometry(QtCore.QRect(430, 30, 61, 71))
        self.Benton.setStyleSheet("")
        self.Benton.setText("")
        self.Benton.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Benton.setObjectName("Benton")
        self.Carroll = QtWidgets.QLabel(self.centralwidget)
        self.Carroll.setGeometry(QtCore.QRect(600, 30, 61, 71))
        self.Carroll.setStyleSheet("")
        self.Carroll.setText("")
        self.Carroll.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Carroll.setObjectName("Carroll")
        self.Boone = QtWidgets.QLabel(self.centralwidget)
        self.Boone.setGeometry(QtCore.QRect(700, 40, 61, 71))
        self.Boone.setStyleSheet("")
        self.Boone.setText("")
        self.Boone.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Boone.setObjectName("Boone")
        self.Marion = QtWidgets.QLabel(self.centralwidget)
        self.Marion.setGeometry(QtCore.QRect(790, 60, 61, 71))
        self.Marion.setStyleSheet("")
        self.Marion.setText("")
        self.Marion.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Marion.setObjectName("Marion")
        self.Baxter = QtWidgets.QLabel(self.centralwidget)
        self.Baxter.setGeometry(QtCore.QRect(880, 40, 61, 71))
        self.Baxter.setStyleSheet("")
        self.Baxter.setText("")
        self.Baxter.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Baxter.setObjectName("Baxter")
        self.Fulton = QtWidgets.QLabel(self.centralwidget)
        self.Fulton.setGeometry(QtCore.QRect(1010, 20, 61, 71))
        self.Fulton.setStyleSheet("")
        self.Fulton.setText("")
        self.Fulton.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Fulton.setObjectName("Fulton")
        self.Randolph = QtWidgets.QLabel(self.centralwidget)
        self.Randolph.setGeometry(QtCore.QRect(1190, 30, 61, 71))
        self.Randolph.setStyleSheet("")
        self.Randolph.setText("")
        self.Randolph.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Randolph.setObjectName("Randolph")
        self.Clay = QtWidgets.QLabel(self.centralwidget)
        self.Clay.setGeometry(QtCore.QRect(1340, 20, 61, 71))
        self.Clay.setStyleSheet("")
        self.Clay.setText("")
        self.Clay.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Clay.setObjectName("Clay")
        self.Washington = QtWidgets.QLabel(self.centralwidget)
        self.Washington.setGeometry(QtCore.QRect(430, 140, 61, 71))
        self.Washington.setStyleSheet("")
        self.Washington.setText("")
        self.Washington.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Washington.setObjectName("Washington")
        self.Madison = QtWidgets.QLabel(self.centralwidget)
        self.Madison.setGeometry(QtCore.QRect(550, 130, 61, 71))
        self.Madison.setStyleSheet("")
        self.Madison.setText("")
        self.Madison.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Madison.setObjectName("Madison")
        self.Newton = QtWidgets.QLabel(self.centralwidget)
        self.Newton.setGeometry(QtCore.QRect(670, 160, 61, 71))
        self.Newton.setStyleSheet("")
        self.Newton.setText("")
        self.Newton.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Newton.setObjectName("Newton")
        self.Searcy = QtWidgets.QLabel(self.centralwidget)
        self.Searcy.setGeometry(QtCore.QRect(800, 160, 61, 71))
        self.Searcy.setStyleSheet("")
        self.Searcy.setText("")
        self.Searcy.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Searcy.setObjectName("Searcy")
        self.Stone = QtWidgets.QLabel(self.centralwidget)
        self.Stone.setGeometry(QtCore.QRect(920, 180, 61, 71))
        self.Stone.setStyleSheet("")
        self.Stone.setText("")
        self.Stone.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Stone.setObjectName("Stone")
        self.Izard = QtWidgets.QLabel(self.centralwidget)
        self.Izard.setGeometry(QtCore.QRect(980, 110, 61, 71))
        self.Izard.setStyleSheet("")
        self.Izard.setText("")
        self.Izard.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Izard.setObjectName("Izard")
        self.Sharp = QtWidgets.QLabel(self.centralwidget)
        self.Sharp.setGeometry(QtCore.QRect(1070, 100, 61, 71))
        self.Sharp.setStyleSheet("")
        self.Sharp.setText("")
        self.Sharp.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Sharp.setObjectName("Sharp")
        self.Lawrence = QtWidgets.QLabel(self.centralwidget)
        self.Lawrence.setGeometry(QtCore.QRect(1170, 130, 61, 71))
        self.Lawrence.setStyleSheet("")
        self.Lawrence.setText("")
        self.Lawrence.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Lawrence.setObjectName("Lawrence")
        self.Greene = QtWidgets.QLabel(self.centralwidget)
        self.Greene.setGeometry(QtCore.QRect(1300, 100, 61, 71))
        self.Greene.setStyleSheet("")
        self.Greene.setText("")
        self.Greene.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Greene.setObjectName("Greene")
        self.Mississippi = QtWidgets.QLabel(self.centralwidget)
        self.Mississippi.setGeometry(QtCore.QRect(1420, 190, 61, 71))
        self.Mississippi.setStyleSheet("")
        self.Mississippi.setText("")
        self.Mississippi.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Mississippi.setObjectName("Mississippi")
        self.Craighead = QtWidgets.QLabel(self.centralwidget)
        self.Craighead.setGeometry(QtCore.QRect(1280, 180, 61, 71))
        self.Craighead.setStyleSheet("")
        self.Craighead.setText("")
        self.Craighead.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Craighead.setObjectName("Craighead")
        self.Poinsett = QtWidgets.QLabel(self.centralwidget)
        self.Poinsett.setGeometry(QtCore.QRect(1280, 260, 61, 71))
        self.Poinsett.setStyleSheet("")
        self.Poinsett.setText("")
        self.Poinsett.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Poinsett.setObjectName("Poinsett")
        self.Jackson = QtWidgets.QLabel(self.centralwidget)
        self.Jackson.setGeometry(QtCore.QRect(1150, 250, 61, 71))
        self.Jackson.setStyleSheet("")
        self.Jackson.setText("")
        self.Jackson.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Jackson.setObjectName("Jackson")
        self.Independence = QtWidgets.QLabel(self.centralwidget)
        self.Independence.setGeometry(QtCore.QRect(1060, 210, 61, 71))
        self.Independence.setStyleSheet("")
        self.Independence.setText("")
        self.Independence.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Independence.setObjectName("Independence")
        self.Cleburne = QtWidgets.QLabel(self.centralwidget)
        self.Cleburne.setGeometry(QtCore.QRect(950, 270, 61, 71))
        self.Cleburne.setStyleSheet("")
        self.Cleburne.setText("")
        self.Cleburne.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Cleburne.setObjectName("Cleburne")
        self.White = QtWidgets.QLabel(self.centralwidget)
        self.White.setGeometry(QtCore.QRect(1020, 360, 61, 71))
        self.White.setStyleSheet("")
        self.White.setText("")
        self.White.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.White.setObjectName("White")
        self.Cross = QtWidgets.QLabel(self.centralwidget)
        self.Cross.setGeometry(QtCore.QRect(1250, 340, 61, 71))
        self.Cross.setStyleSheet("")
        self.Cross.setText("")
        self.Cross.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Cross.setObjectName("Cross")
        self.Crittenden = QtWidgets.QLabel(self.centralwidget)
        self.Crittenden.setGeometry(QtCore.QRect(1370, 360, 61, 71))
        self.Crittenden.setStyleSheet("")
        self.Crittenden.setText("")
        self.Crittenden.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Crittenden.setObjectName("Crittenden")
        self.Woodruff = QtWidgets.QLabel(self.centralwidget)
        self.Woodruff.setGeometry(QtCore.QRect(1140, 380, 61, 71))
        self.Woodruff.setStyleSheet("")
        self.Woodruff.setText("")
        self.Woodruff.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Woodruff.setObjectName("Woodruff")
        self.StFrancis = QtWidgets.QLabel(self.centralwidget)
        self.StFrancis.setGeometry(QtCore.QRect(1260, 420, 61, 71))
        self.StFrancis.setStyleSheet("")
        self.StFrancis.setText("")
        self.StFrancis.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.StFrancis.setObjectName("StFrancis")
        self.Lee = QtWidgets.QLabel(self.centralwidget)
        self.Lee.setGeometry(QtCore.QRect(1250, 490, 61, 71))
        self.Lee.setStyleSheet("")
        self.Lee.setText("")
        self.Lee.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Lee.setObjectName("Lee")
        self.Phillips = QtWidgets.QLabel(self.centralwidget)
        self.Phillips.setGeometry(QtCore.QRect(1240, 580, 61, 71))
        self.Phillips.setStyleSheet("")
        self.Phillips.setText("")
        self.Phillips.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Phillips.setObjectName("Phillips")
        self.Monroe = QtWidgets.QLabel(self.centralwidget)
        self.Monroe.setGeometry(QtCore.QRect(1140, 520, 61, 71))
        self.Monroe.setStyleSheet("")
        self.Monroe.setText("")
        self.Monroe.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Monroe.setObjectName("Monroe")
        self.Prairie = QtWidgets.QLabel(self.centralwidget)
        self.Prairie.setGeometry(QtCore.QRect(1070, 480, 61, 71))
        self.Prairie.setStyleSheet("")
        self.Prairie.setText("")
        self.Prairie.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Prairie.setObjectName("Prairie")
        self.VanBuren = QtWidgets.QLabel(self.centralwidget)
        self.VanBuren.setGeometry(QtCore.QRect(830, 260, 61, 71))
        self.VanBuren.setStyleSheet("")
        self.VanBuren.setText("")
        self.VanBuren.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.VanBuren.setObjectName("VanBuren")
        self.Faulkner = QtWidgets.QLabel(self.centralwidget)
        self.Faulkner.setGeometry(QtCore.QRect(880, 380, 61, 71))
        self.Faulkner.setStyleSheet("")
        self.Faulkner.setText("")
        self.Faulkner.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Faulkner.setObjectName("Faulkner")
        self.Lonoke = QtWidgets.QLabel(self.centralwidget)
        self.Lonoke.setGeometry(QtCore.QRect(990, 500, 61, 71))
        self.Lonoke.setStyleSheet("")
        self.Lonoke.setText("")
        self.Lonoke.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Lonoke.setObjectName("Lonoke")
        self.Pulaski = QtWidgets.QLabel(self.centralwidget)
        self.Pulaski.setGeometry(QtCore.QRect(890, 500, 61, 71))
        self.Pulaski.setStyleSheet("")
        self.Pulaski.setText("")
        self.Pulaski.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Pulaski.setObjectName("Pulaski")
        self.Crawford = QtWidgets.QLabel(self.centralwidget)
        self.Crawford.setGeometry(QtCore.QRect(420, 250, 61, 71))
        self.Crawford.setStyleSheet("")
        self.Crawford.setText("")
        self.Crawford.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Crawford.setObjectName("Crawford")
        self.Franklin = QtWidgets.QLabel(self.centralwidget)
        self.Franklin.setGeometry(QtCore.QRect(520, 270, 61, 71))
        self.Franklin.setStyleSheet("")
        self.Franklin.setText("")
        self.Franklin.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Franklin.setObjectName("Franklin")
        self.Johnson = QtWidgets.QLabel(self.centralwidget)
        self.Johnson.setGeometry(QtCore.QRect(610, 260, 61, 71))
        self.Johnson.setStyleSheet("")
        self.Johnson.setText("")
        self.Johnson.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Johnson.setObjectName("Johnson")
        self.Pope = QtWidgets.QLabel(self.centralwidget)
        self.Pope.setGeometry(QtCore.QRect(710, 300, 61, 71))
        self.Pope.setStyleSheet("")
        self.Pope.setText("")
        self.Pope.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Pope.setObjectName("Pope")
        self.Conway = QtWidgets.QLabel(self.centralwidget)
        self.Conway.setGeometry(QtCore.QRect(800, 350, 61, 71))
        self.Conway.setStyleSheet("")
        self.Conway.setText("")
        self.Conway.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Conway.setObjectName("Conway")
        self.Sebastian = QtWidgets.QLabel(self.centralwidget)
        self.Sebastian.setGeometry(QtCore.QRect(420, 370, 61, 71))
        self.Sebastian.setStyleSheet("")
        self.Sebastian.setText("")
        self.Sebastian.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Sebastian.setObjectName("Sebastian")
        self.Logan = QtWidgets.QLabel(self.centralwidget)
        self.Logan.setGeometry(QtCore.QRect(570, 350, 61, 71))
        self.Logan.setStyleSheet("")
        self.Logan.setText("")
        self.Logan.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Logan.setObjectName("Logan")
        self.Yell = QtWidgets.QLabel(self.centralwidget)
        self.Yell.setGeometry(QtCore.QRect(620, 430, 61, 71))
        self.Yell.setStyleSheet("")
        self.Yell.setText("")
        self.Yell.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Yell.setObjectName("Yell")
        self.Perry = QtWidgets.QLabel(self.centralwidget)
        self.Perry.setGeometry(QtCore.QRect(740, 440, 61, 71))
        self.Perry.setStyleSheet("")
        self.Perry.setText("")
        self.Perry.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Perry.setObjectName("Perry")
        self.Scott = QtWidgets.QLabel(self.centralwidget)
        self.Scott.setGeometry(QtCore.QRect(480, 470, 61, 71))
        self.Scott.setStyleSheet("")
        self.Scott.setText("")
        self.Scott.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Scott.setObjectName("Scott")
        self.Polk = QtWidgets.QLabel(self.centralwidget)
        self.Polk.setGeometry(QtCore.QRect(440, 570, 61, 71))
        self.Polk.setStyleSheet("")
        self.Polk.setText("")
        self.Polk.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Polk.setObjectName("Polk")
        self.Montgomery = QtWidgets.QLabel(self.centralwidget)
        self.Montgomery.setGeometry(QtCore.QRect(570, 560, 61, 71))
        self.Montgomery.setStyleSheet("")
        self.Montgomery.setText("")
        self.Montgomery.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Montgomery.setObjectName("Montgomery")
        self.Garland = QtWidgets.QLabel(self.centralwidget)
        self.Garland.setGeometry(QtCore.QRect(680, 550, 61, 71))
        self.Garland.setStyleSheet("")
        self.Garland.setText("")
        self.Garland.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Garland.setObjectName("Garland")
        self.Saline = QtWidgets.QLabel(self.centralwidget)
        self.Saline.setGeometry(QtCore.QRect(790, 530, 61, 71))
        self.Saline.setStyleSheet("")
        self.Saline.setText("")
        self.Saline.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Saline.setObjectName("Saline")
        self.Arkansas = QtWidgets.QLabel(self.centralwidget)
        self.Arkansas.setGeometry(QtCore.QRect(1110, 620, 61, 71))
        self.Arkansas.setStyleSheet("")
        self.Arkansas.setText("")
        self.Arkansas.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Arkansas.setObjectName("Arkansas")
        self.Jefferson = QtWidgets.QLabel(self.centralwidget)
        self.Jefferson.setGeometry(QtCore.QRect(970, 640, 61, 71))
        self.Jefferson.setStyleSheet("")
        self.Jefferson.setText("")
        self.Jefferson.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Jefferson.setObjectName("Jefferson")
        self.Grant = QtWidgets.QLabel(self.centralwidget)
        self.Grant.setGeometry(QtCore.QRect(860, 640, 61, 71))
        self.Grant.setStyleSheet("")
        self.Grant.setText("")
        self.Grant.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Grant.setObjectName("Grant")
        self.HotSpring = QtWidgets.QLabel(self.centralwidget)
        self.HotSpring.setGeometry(QtCore.QRect(760, 640, 61, 71))
        self.HotSpring.setStyleSheet("")
        self.HotSpring.setText("")
        self.HotSpring.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.HotSpring.setObjectName("HotSpring")
        self.Desha = QtWidgets.QLabel(self.centralwidget)
        self.Desha.setGeometry(QtCore.QRect(1120, 770, 61, 71))
        self.Desha.setStyleSheet("")
        self.Desha.setText("")
        self.Desha.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Desha.setObjectName("Desha")
        self.Lincoln = QtWidgets.QLabel(self.centralwidget)
        self.Lincoln.setGeometry(QtCore.QRect(1020, 740, 61, 71))
        self.Lincoln.setStyleSheet("")
        self.Lincoln.setText("")
        self.Lincoln.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Lincoln.setObjectName("Lincoln")
        self.Sevier = QtWidgets.QLabel(self.centralwidget)
        self.Sevier.setGeometry(QtCore.QRect(430, 730, 61, 71))
        self.Sevier.setStyleSheet("")
        self.Sevier.setText("")
        self.Sevier.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Sevier.setObjectName("Sevier")
        self.Howard = QtWidgets.QLabel(self.centralwidget)
        self.Howard.setGeometry(QtCore.QRect(500, 710, 61, 71))
        self.Howard.setStyleSheet("")
        self.Howard.setText("")
        self.Howard.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Howard.setObjectName("Howard")
        self.Pike = QtWidgets.QLabel(self.centralwidget)
        self.Pike.setGeometry(QtCore.QRect(570, 670, 61, 71))
        self.Pike.setStyleSheet("")
        self.Pike.setText("")
        self.Pike.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Pike.setObjectName("Pike")
        self.Clark = QtWidgets.QLabel(self.centralwidget)
        self.Clark.setGeometry(QtCore.QRect(680, 710, 61, 71))
        self.Clark.setStyleSheet("")
        self.Clark.setText("")
        self.Clark.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Clark.setObjectName("Clark")
        self.Dallas = QtWidgets.QLabel(self.centralwidget)
        self.Dallas.setGeometry(QtCore.QRect(810, 730, 61, 71))
        self.Dallas.setStyleSheet("")
        self.Dallas.setText("")
        self.Dallas.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Dallas.setObjectName("Dallas")
        self.Cleveland = QtWidgets.QLabel(self.centralwidget)
        self.Cleveland.setGeometry(QtCore.QRect(920, 760, 61, 71))
        self.Cleveland.setStyleSheet("")
        self.Cleveland.setText("")
        self.Cleveland.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Cleveland.setObjectName("Cleveland")
        self.Drew = QtWidgets.QLabel(self.centralwidget)
        self.Drew.setGeometry(QtCore.QRect(1030, 850, 61, 71))
        self.Drew.setStyleSheet("")
        self.Drew.setText("")
        self.Drew.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Drew.setObjectName("Drew")
        self.Chicot = QtWidgets.QLabel(self.centralwidget)
        self.Chicot.setGeometry(QtCore.QRect(1130, 950, 61, 71))
        self.Chicot.setStyleSheet("")
        self.Chicot.setText("")
        self.Chicot.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Chicot.setObjectName("Chicot")
        self.LittleRiver = QtWidgets.QLabel(self.centralwidget)
        self.LittleRiver.setGeometry(QtCore.QRect(410, 820, 61, 71))
        self.LittleRiver.setStyleSheet("")
        self.LittleRiver.setText("")
        self.LittleRiver.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.LittleRiver.setObjectName("LittleRiver")
        self.Hempstead = QtWidgets.QLabel(self.centralwidget)
        self.Hempstead.setGeometry(QtCore.QRect(570, 800, 61, 71))
        self.Hempstead.setStyleSheet("")
        self.Hempstead.setText("")
        self.Hempstead.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Hempstead.setObjectName("Hempstead")
        self.Miller = QtWidgets.QLabel(self.centralwidget)
        self.Miller.setGeometry(QtCore.QRect(510, 920, 61, 71))
        self.Miller.setStyleSheet("")
        self.Miller.setText("")
        self.Miller.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Miller.setObjectName("Miller")
        self.Lafayette = QtWidgets.QLabel(self.centralwidget)
        self.Lafayette.setGeometry(QtCore.QRect(590, 920, 61, 71))
        self.Lafayette.setStyleSheet("")
        self.Lafayette.setText("")
        self.Lafayette.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Lafayette.setObjectName("Lafayette")
        self.Nevada = QtWidgets.QLabel(self.centralwidget)
        self.Nevada.setGeometry(QtCore.QRect(660, 830, 61, 71))
        self.Nevada.setStyleSheet("")
        self.Nevada.setText("")
        self.Nevada.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Nevada.setObjectName("Nevada")
        self.Columbia = QtWidgets.QLabel(self.centralwidget)
        self.Columbia.setGeometry(QtCore.QRect(670, 960, 61, 71))
        self.Columbia.setStyleSheet("")
        self.Columbia.setText("")
        self.Columbia.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Columbia.setObjectName("Columbia")
        self.Ouachita = QtWidgets.QLabel(self.centralwidget)
        self.Ouachita.setGeometry(QtCore.QRect(750, 840, 61, 71))
        self.Ouachita.setStyleSheet("")
        self.Ouachita.setText("")
        self.Ouachita.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Ouachita.setObjectName("Ouachita")
        self.Calhoun = QtWidgets.QLabel(self.centralwidget)
        self.Calhoun.setGeometry(QtCore.QRect(840, 860, 61, 71))
        self.Calhoun.setStyleSheet("")
        self.Calhoun.setText("")
        self.Calhoun.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Calhoun.setObjectName("Calhoun")
        self.Bradley = QtWidgets.QLabel(self.centralwidget)
        self.Bradley.setGeometry(QtCore.QRect(930, 890, 61, 71))
        self.Bradley.setStyleSheet("")
        self.Bradley.setText("")
        self.Bradley.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Bradley.setObjectName("Bradley")
        self.Union = QtWidgets.QLabel(self.centralwidget)
        self.Union.setGeometry(QtCore.QRect(820, 970, 61, 71))
        self.Union.setStyleSheet("")
        self.Union.setText("")
        self.Union.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Union.setObjectName("Union")
        self.Ashley = QtWidgets.QLabel(self.centralwidget)
        self.Ashley.setGeometry(QtCore.QRect(1020, 960, 61, 71))
        self.Ashley.setStyleSheet("")
        self.Ashley.setText("")
        self.Ashley.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.Ashley.setObjectName("Ashley")
        self.legend = QtWidgets.QWidget(self.centralwidget)
        self.legend.setGeometry(QtCore.QRect(20, 170, 311, 574))
        self.legend.setObjectName("legend")
        self.gridLayout = QtWidgets.QGridLayout(self.legend)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hostile = QtWidgets.QLabel(self.legend)
        self.hostile.setAutoFillBackground(False)
        self.hostile.setText("")
        self.hostile.setPixmap(QtGui.QPixmap(":/Images/1f621hostile.png"))
        self.hostile.setObjectName("hostile")
        self.gridLayout.addWidget(self.hostile, 6, 0, 1, 1)
        self.bored = QtWidgets.QLabel(self.legend)
        self.bored.setAutoFillBackground(False)
        self.bored.setText("")
        self.bored.setPixmap(QtGui.QPixmap(":/Images/1f634bored.png"))
        self.bored.setObjectName("bored")
        self.gridLayout.addWidget(self.bored, 7, 0, 1, 1)
        self.relaxed = QtWidgets.QLabel(self.legend)
        self.relaxed.setAutoFillBackground(False)
        self.relaxed.setText("")
        self.relaxed.setPixmap(QtGui.QPixmap(":/Images/1f60c.relaxedsvg.png"))
        self.relaxed.setObjectName("relaxed")
        self.gridLayout.addWidget(self.relaxed, 2, 0, 1, 1)
        self.dependent = QtWidgets.QLabel(self.legend)
        self.dependent.setAutoFillBackground(False)
        self.dependent.setText("")
        self.dependent.setPixmap(QtGui.QPixmap(":/Images/1f605dependent.png"))
        self.dependent.setObjectName("dependent")
        self.gridLayout.addWidget(self.dependent, 1, 0, 1, 1)
        self.anxious = QtWidgets.QLabel(self.legend)
        self.anxious.setAutoFillBackground(False)
        self.anxious.setText("")
        self.anxious.setPixmap(QtGui.QPixmap(":/Images/1f616anxious.png"))
        self.anxious.setObjectName("anxious")
        self.gridLayout.addWidget(self.anxious, 4, 0, 1, 1)
        self.exuberant = QtWidgets.QLabel(self.legend)
        self.exuberant.setAutoFillBackground(False)
        self.exuberant.setText("")
        self.exuberant.setPixmap(QtGui.QPixmap(":/Images/1f601exuberant.png"))
        self.exuberant.setObjectName("exuberant")
        self.gridLayout.addWidget(self.exuberant, 0, 0, 1, 1)
        self.docile = QtWidgets.QLabel(self.legend)
        self.docile.setAutoFillBackground(False)
        self.docile.setText("")
        self.docile.setPixmap(QtGui.QPixmap(":/Images/1f610docile.png"))
        self.docile.setObjectName("docile")
        self.gridLayout.addWidget(self.docile, 3, 0, 1, 1)
        self.disdainful = QtWidgets.QLabel(self.legend)
        self.disdainful.setAutoFillBackground(False)
        self.disdainful.setText("")
        self.disdainful.setPixmap(QtGui.QPixmap(":/Images/1f61edisdainful.png"))
        self.disdainful.setObjectName("disdainful")
        self.gridLayout.addWidget(self.disdainful, 5, 0, 1, 1)
        self.exuberant_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.exuberant_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.exuberant_l.setFont(font)
        self.exuberant_l.setAcceptDrops(False)
        self.exuberant_l.setObjectName("exuberant_l")
        self.gridLayout.addWidget(self.exuberant_l, 0, 1, 1, 1)
        self.dependent_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dependent_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.dependent_l.setFont(font)
        self.dependent_l.setAcceptDrops(False)
        self.dependent_l.setObjectName("dependent_l")
        self.gridLayout.addWidget(self.dependent_l, 1, 1, 1, 1)
        self.relaxed_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.relaxed_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.relaxed_l.setFont(font)
        self.relaxed_l.setAcceptDrops(False)
        self.relaxed_l.setObjectName("relaxed_l")
        self.gridLayout.addWidget(self.relaxed_l, 2, 1, 1, 1)
        self.docile_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.docile_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.docile_l.setFont(font)
        self.docile_l.setAcceptDrops(False)
        self.docile_l.setObjectName("docile_l")
        self.gridLayout.addWidget(self.docile_l, 3, 1, 1, 1)
        self.anxious_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.anxious_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.anxious_l.setFont(font)
        self.anxious_l.setAcceptDrops(False)
        self.anxious_l.setObjectName("anxious_l")
        self.gridLayout.addWidget(self.anxious_l, 4, 1, 1, 1)
        self.disdainful_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.disdainful_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.disdainful_l.setFont(font)
        self.disdainful_l.setAcceptDrops(False)
        self.disdainful_l.setObjectName("disdainful_l")
        self.gridLayout.addWidget(self.disdainful_l, 5, 1, 1, 1)
        self.hostile_l = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.hostile_l.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.hostile_l.setFont(font)
        self.hostile_l.setAcceptDrops(False)
        self.hostile_l.setObjectName("hostile_l")
        self.gridLayout.addWidget(self.hostile_l, 6, 1, 1, 1)
        self.bored_label = QtWidgets.QLabel(self.legend)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.bored_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bored_label.setFont(font)
        self.bored_label.setAcceptDrops(False)
        self.bored_label.setObjectName("bored_label")
        self.gridLayout.addWidget(self.bored_label, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exuberant_l.setText(_translate("MainWindow", "Exuberant"))
        self.dependent_l.setText(_translate("MainWindow", "Dependent"))
        self.relaxed_l.setText(_translate("MainWindow", "Relaxed"))
        self.docile_l.setText(_translate("MainWindow", "Docile"))
        self.anxious_l.setText(_translate("MainWindow", "Anxious"))
        self.disdainful_l.setText(_translate("MainWindow", "Disdainful"))
        self.hostile_l.setText(_translate("MainWindow", "Hostile"))
        self.bored_label.setText(_translate("MainWindow", "Bored"))

import tsaimg_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()()
    sys.exit(app.exec_())

